### ISSUE TITLE
Don't use std::function

### ISSUE THREAD

**Issue by eyalroz** [martin-olivier/dylib#20]
std::function is a heavy container, whose main use is encapsulating potentially complex invokable objects. See [this discussion](https://stackoverflow.com/questions/20353210); why use it? A simple (typed) function pointer should probably do nicely.

**Comment by martin-olivier** [comment]
Hello, I just made your requested changes on https://github.com/martin-olivier/dylib/pull/21
Feel free to make a review on those changes, after what i will merge them

**Comment by eyalroz** [comment]
I am actually not entire sure that it's better to "roll everything up" into a single function. It has some elegance benefit, but what if, in the future, you wanted to differentiate their behavior somehow? But maybe that's not interesting/not relevant. Like I said, no strong opinion.

**Comment by martin-olivier** [comment]
Hello,
Finally, i kept the original names `get_function` and `get_variable` to be able to make specific variable / function mangling for this issue https://github.com/martin-olivier/dylib/issues/27.
`get_function` now returns a function reference instead of an `std::function`

Merged into `dev` branch at https://github.com/martin-olivier/dylib/commit/a3ef5e74ff5871101b376c9d2e341a49db286604
